# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 22:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatters', '0002_auto_20170129_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatter',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
