# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 01:45
from __future__ import unicode_literals

import chatters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatters', '0004_auto_20170129_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatter',
            name='content',
            field=models.TextField(max_length=150, validators=[chatters.models.validate_content]),
        ),
    ]
